version: '3'

services:
  nginx: 
    restart: always
    build:
      context: .
      dockerfile: ./_/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./_/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - back-flask
      - back-fastapi
      - back-django
  
  back-flask:
    restart: 'always'
    build: 
      context: .
      dockerfile: ./_/back/flask/Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh
    expose:
      - 5000

  back-fastapi:
    restart: 'always'
    build: 
      context: .
      dockerfile: ./_/back/fastapi/Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh
    expose:
      - 8000

  back-django:
    restart: 'always'
    build: 
      context: .
      dockerfile: ./_/back/django/Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh
    expose:
      - 8001